INSERT INTO application VALUES ('COMMON','Sekundere adresser som benyttes av sidene, bl.a. fonter, javascript, goole amnalytics');
INSERT INTO application VALUES ('pgs','');
INSERT INTO application VALUES ('Feide','');
INSERT INTO application VALUES ('Allkunne','');
INSERT INTO application VALUES ('Bioteknologirådet','');
INSERT INTO application VALUES ('Brønnøysundregisteret','');
INSERT INTO application VALUES ('FN','Globalis');
INSERT INTO application VALUES ('LEXIN','Ordbøker');
INSERT INTO application VALUES ('Lovdata',''); 
INSERT INTO application VALUES ('NDLA','Digitale nettressurser');
INSERT INTO application VALUES ('Norges bank','Videoer er ikke inkludert');
INSERT INTO application VALUES ('Norsksidene','');
INSERT INTO application VALUES ('NUPI','Norsk Utenrikspolitist Institutt');
INSERT INTO application VALUES ('Psykologisk tidsskrift','');
INSERT INTO application VALUES ('Regjeringen','');
INSERT INTO application VALUES ('Webprogrammering','Ressurser for bl.a. HTML og JavaScript');
INSERT INTO application VALUES ('Språkrådets ordbøker','');
INSERT INTO application VALUES ('Store Norske leksikon','');
INSERT INTO application VALUES ('Skriveverktøy','Videoer er ikke inkludert');
INSERT INTO application VALUES ('Statistisk Sentralbyrå','');
INSERT INTO application VALUES ('Stortinget','');
INSERT INTO application VALUES ('Samiske ressurser','Disse er foreløpig ikke kontrollert');
INSERT INTO application VALUES ('Finske ressurser','Disse er foreløpig ikke kontrollert');
INSERT INTO application VALUES ('Yrkesfag','');
INSERT INTO application VALUES ('Helse og oppvekst','');
INSERT INTO application VALUES ('Norsk helseinformatikk','');
INSERT INTO application VALUES ('Felleskatalogen','');
INSERT INTO application VALUES ('Teknikk og industriell produksjon','');
INSERT INTO application VALUES ('Studieforberedende utdanningsprogram','');
INSERT INTO application VALUES ('Medier og kommunikasjon','');
INSERT INTO application VALUES ('Tegnspråk','');
INSERT INTO application VALUES ('','');
INSERT INTO application VALUES ('','');
INSERT INTO application VALUES ('','');
INSERT INTO application VALUES ('','');
INSERT INTO application VALUES ('','');
INSERT INTO application VALUES ('','');


